work_dir: ./work_dir/smarthome/xview1/unik_bone
model_saved_name: ./runs/smarthome/smarthome_cv1_unik_bone
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/smarthome/xview1/train_data_bone.npy
  label_path: ./data/smarthome/xview1/train_label.pkl
  debug: False
  random_choose: True
  random_shift: False
  random_move: True
  window_size: 400
  normalization: False

test_feeder_args:
  data_path: ./data/smarthome/xview1/val_data_bone.npy
  label_path: ./data/smarthome/xview1/val_label.pkl
  random_choose: True
  window_size: 400

# model
model: model.classifier.Model
model_args:
  in_channels: 2
  num_class: 19
  num_joints: 17
  num_person: 2
  weights: ./weights/weights-posetics.pt
  backbone_fixed: False
  
weight_decay: 0.0001
base_lr: 0.1
step: [10, 20]

# training
device: [0]
batch_size: 8
test_batch_size: 32
num_epoch: 30
nesterov: True
