# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_bone.npy
  label_path: ./data/ntu120/xsub/val_label.pkl
  debug: False

# model
model: model.backbone_unik.UNIK
model_args:
  num_class: 120
  num_joints: 25
  num_person: 2
  in_channels: 3
  num_heads: 12
  
# test
phase: test
device: [0, 1]
test_batch_size: 64
weights: ./runs/ntu120/ntu120_cs_unik_bone-59-118140.pt
work_dir: ./work_dir/ntu120/xsub/unik_test_bone
model_saved_name: ./runs/ntu120/ntu120_cs_unik_test_bone
save_score: True
