# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/smarthome/xview2/val_data_joint.npy
  label_path: ./data/smarthome/xview2/val_label.pkl
  debug: False
# model
model: model.classifier.Model
model_args:
  num_class: 19
  num_joints: 17
  num_person: 2
  in_channels: 2
  num_heads: 3


# test 
phase: test
device: [0, 1]
test_batch_size: 16
weights: runs/smarthome/smarthome_cv2_unik_joint-49-20300.pt
work_dir: ./work_dir/smarthome/xview2/unik_test_joint
model_saved_name: ./runs/smarthome/smarthome_cv2_unik_test_joint
save_score: True
