# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/posetics/val_data_joint.npy
  label_path: ./data/posetics/val_label.pkl
  debug: False

# model
model: model.backbone_unik.UNIK
model_args:
  num_class: 320
  num_person: 2
  num_joints: 17
  num_heads: 3
  tau: 1


# test 
phase: test
device: [0, 1]
test_batch_size: 64
weights: ./runs/posetics/ #TODO
work_dir: ./work_dir/posetics/unik_test_joint
model_saved_name: ./runs/posetics/posetics_unik_test_joint
save_score: True
