work_dir: ./work_dir/ntu/xsub/unik_bone
model_saved_name: ./runs/ntu/ntu_cs_unik_bone
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu/xsub/train_data_bone.npy
  label_path: ./data/ntu/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu/xsub/val_data_bone.npy
  label_path: ./data/ntu/xsub/val_label.pkl

# model
model: model.backbone_unik.UNIK
model_args:
  num_class: 60
  num_joints: 25
  num_person: 2
  in_channels: 3
  num_heads: 12

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0, 1, 2, 3]
batch_size: 32
test_batch_size: 64
num_epoch: 50
nesterov: True

