# feedebasbaseer
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/penn/val_data_joint.npy
  label_path: ./data/penn/val_label.pkl
  debug: False

# model
model: model.classifier.Model
model_args:
  num_class: 15
  num_joints: 17
  num_person: 2
  num_heads: 3

# test
phase: test
device: [0]
test_batch_size: 8
weights: ./runs/penn/penn_unik_joint-29-4710.pt
work_dir: ./work_dir/penn/unik_test_joint
model_saved_name: ./runs/penn/penn_unik_test_joint
save_score: True

